{"id":545899598,"status":"canceled","stage":"stage-4","name":"library:ci-corn","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.404Z","started_at":null,"finished_at":"2020-05-10T19:28:41.936Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899598","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899597,"status":"canceled","stage":"stage-3","name":"library:ci-math-classes","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.385Z","started_at":null,"finished_at":"2020-05-10T19:28:41.923Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899597","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899596,"status":"canceled","stage":"stage-3","name":"library:ci-color","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.368Z","started_at":null,"finished_at":"2020-05-10T19:28:41.912Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899596","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899595,"status":"canceled","stage":"stage-2","name":"plugin:ci-relation_algebra","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.350Z","started_at":null,"finished_at":"2020-05-10T19:28:41.901Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899595","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899594,"status":"canceled","stage":"stage-2","name":"plugin:ci-quickchick","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.335Z","started_at":null,"finished_at":"2020-05-10T19:28:41.890Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899594","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899593,"status":"canceled","stage":"stage-2","name":"plugin:ci-perennial","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.319Z","started_at":null,"finished_at":"2020-05-10T19:28:41.880Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899593","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899592,"status":"canceled","stage":"stage-2","name":"plugin:ci-paramcoq","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.304Z","started_at":null,"finished_at":"2020-05-10T19:28:41.869Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899592","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899591,"status":"canceled","stage":"stage-2","name":"plugin:ci-mtac2","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.288Z","started_at":null,"finished_at":"2020-05-10T19:28:41.859Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899591","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899590,"status":"canceled","stage":"stage-2","name":"plugin:ci-fiat_parsers","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.272Z","started_at":null,"finished_at":"2020-05-10T19:28:41.848Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899590","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899589,"status":"canceled","stage":"stage-2","name":"plugin:ci-equations","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.256Z","started_at":null,"finished_at":"2020-05-10T19:28:41.837Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899589","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899588,"status":"canceled","stage":"stage-2","name":"plugin:ci-elpi","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.240Z","started_at":null,"finished_at":"2020-05-10T19:28:41.825Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899588","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899587,"status":"canceled","stage":"stage-2","name":"plugin:ci-coqhammer","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.225Z","started_at":null,"finished_at":"2020-05-10T19:28:41.814Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899587","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899586,"status":"canceled","stage":"stage-2","name":"plugin:ci-coq_dpdgraph","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.210Z","started_at":null,"finished_at":"2020-05-10T19:28:41.803Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899586","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899585,"status":"canceled","stage":"stage-2","name":"plugin:ci-bignums","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.195Z","started_at":null,"finished_at":"2020-05-10T19:28:41.792Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899585","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899584,"status":"canceled","stage":"stage-2","name":"plugin:ci-aac_tactics","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.180Z","started_at":null,"finished_at":"2020-05-10T19:28:41.780Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899584","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899583,"status":"canceled","stage":"stage-2","name":"library:ci-vst","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.165Z","started_at":null,"finished_at":"2020-05-10T19:28:41.769Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899583","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899582,"status":"canceled","stage":"stage-2","name":"library:ci-verdi-raft","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.150Z","started_at":null,"finished_at":"2020-05-10T19:28:41.758Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899582","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899581,"status":"canceled","stage":"stage-2","name":"library:ci-unimath","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.135Z","started_at":null,"finished_at":"2020-05-10T19:28:41.748Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899581","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899580,"status":"canceled","stage":"stage-2","name":"library:ci-tlc","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.120Z","started_at":null,"finished_at":"2020-05-10T19:28:41.737Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899580","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899579,"status":"canceled","stage":"stage-2","name":"library:ci-stdlib2","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.104Z","started_at":null,"finished_at":"2020-05-10T19:28:41.725Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899579","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899578,"status":"canceled","stage":"stage-2","name":"library:ci-sf","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.088Z","started_at":null,"finished_at":"2020-05-10T19:28:41.714Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899578","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899577,"status":"canceled","stage":"stage-2","name":"library:ci-math-comp","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.072Z","started_at":null,"finished_at":"2020-05-10T19:28:41.704Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899577","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899576,"status":"canceled","stage":"stage-2","name":"library:ci-iris-lambda-rust","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.055Z","started_at":null,"finished_at":"2020-05-10T19:28:41.693Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899576","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899575,"status":"canceled","stage":"stage-2","name":"library:ci-hott","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.039Z","started_at":null,"finished_at":"2020-05-10T19:28:41.682Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899575","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899574,"status":"canceled","stage":"stage-2","name":"library:ci-geocoq","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.023Z","started_at":null,"finished_at":"2020-05-10T19:28:41.669Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899574","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899573,"status":"canceled","stage":"stage-2","name":"library:ci-flocq","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:31.008Z","started_at":null,"finished_at":"2020-05-10T19:28:41.657Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899573","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899572,"status":"canceled","stage":"stage-2","name":"library:ci-fiat-crypto-legacy","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.993Z","started_at":null,"finished_at":"2020-05-10T19:28:41.646Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899572","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899571,"status":"canceled","stage":"stage-2","name":"library:ci-fiat-crypto","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.979Z","started_at":null,"finished_at":"2020-05-10T19:28:41.632Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899571","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899570,"status":"canceled","stage":"stage-2","name":"library:ci-fcsl-pcm","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.965Z","started_at":null,"finished_at":"2020-05-10T19:28:41.621Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899570","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899569,"status":"canceled","stage":"stage-2","name":"library:ci-cross-crypto","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.950Z","started_at":null,"finished_at":"2020-05-10T19:28:41.610Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899569","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899568,"status":"canceled","stage":"stage-2","name":"library:ci-coquelicot","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.934Z","started_at":null,"finished_at":"2020-05-10T19:28:41.599Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899568","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899567,"status":"canceled","stage":"stage-2","name":"library:ci-compcert","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.919Z","started_at":null,"finished_at":"2020-05-10T19:28:41.587Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899567","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899566,"status":"canceled","stage":"stage-2","name":"library:ci-bedrock2","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.904Z","started_at":null,"finished_at":"2020-05-10T19:28:41.576Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899566","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899565,"status":"canceled","stage":"stage-2","name":"library:ci-argosy","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.889Z","started_at":null,"finished_at":"2020-05-10T19:28:41.565Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899565","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899564,"status":"canceled","stage":"stage-2","name":"validate:quick","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.872Z","started_at":null,"finished_at":"2020-05-10T19:28:41.554Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899564","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899563,"status":"canceled","stage":"stage-2","name":"validate:edge+flambda","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.857Z","started_at":null,"finished_at":"2020-05-10T19:28:41.543Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899563","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899562,"status":"canceled","stage":"stage-2","name":"validate:base+32bit","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.842Z","started_at":null,"finished_at":"2020-05-10T19:28:41.533Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899562","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899561,"status":"canceled","stage":"stage-2","name":"validate:base","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.826Z","started_at":null,"finished_at":"2020-05-10T19:28:41.523Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899561","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899560,"status":"canceled","stage":"stage-2","name":"test-suite:base+async","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T19:26:30.808Z","started_at":null,"finished_at":"2020-05-10T19:28:41.513Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899560","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899559,"status":"canceled","stage":"stage-2","name":"test-suite:edge:dune:dev","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.790Z","started_at":null,"finished_at":"2020-05-10T19:28:41.503Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899559","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899558,"status":"canceled","stage":"stage-2","name":"test-suite:edge+flambda","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.771Z","started_at":null,"finished_at":"2020-05-10T19:28:41.492Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899558","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899557,"status":"canceled","stage":"stage-2","name":"test-suite:base+32bit","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.709Z","started_at":null,"finished_at":"2020-05-10T19:28:41.479Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899557","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899556,"status":"canceled","stage":"stage-2","name":"test-suite:base","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.689Z","started_at":null,"finished_at":"2020-05-10T19:28:41.468Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899556","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899555,"status":"canceled","stage":"stage-2","name":"doc:ml-api:odoc","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.672Z","started_at":null,"finished_at":"2020-05-10T19:28:41.458Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899555","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899554,"status":"canceled","stage":"stage-2","name":"doc:stdlib:dune","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.652Z","started_at":null,"finished_at":"2020-05-10T19:28:41.447Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899554","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899553,"status":"canceled","stage":"stage-2","name":"doc:refman:dune","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.637Z","started_at":null,"finished_at":"2020-05-10T19:28:41.435Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899553","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899552,"status":"canceled","stage":"stage-2","name":"doc:refman","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.616Z","started_at":null,"finished_at":"2020-05-10T19:28:41.425Z","duration":null,"queued_duration":null,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899552","artifacts":[],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899551,"status":"canceled","stage":"stage-1","name":"plugin:plugin-tutorial","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.584Z","started_at":"2020-05-10T19:26:33.267Z","finished_at":"2020-05-10T19:28:41.413Z","duration":128.145961,"queued_duration":1.413345,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899551","artifacts":[{"file_type":"trace","size":485,"filename":"job.log","file_format":null}],"runner":{"id":44028,"description":"shared-runners-manager-3.gitlab.com","ip_address":"35.196.21.178","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899550,"status":"canceled","stage":"stage-1","name":"test-suite:edge+4.11+trunk+dune","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T19:26:30.569Z","started_at":"2020-05-10T19:26:33.228Z","finished_at":"2020-05-10T19:28:41.401Z","duration":128.173118,"queued_duration":1.403936,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899550","artifacts":[{"file_type":"trace","size":785,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899549,"status":"canceled","stage":"stage-1","name":"pkg:nix","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.550Z","started_at":"2020-05-10T19:26:33.184Z","finished_at":"2020-05-10T19:28:41.386Z","duration":128.201549,"queued_duration":1.391407,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899549","artifacts":[{"file_type":"trace","size":65205,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899547,"status":"canceled","stage":"stage-1","name":"pkg:opam","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.530Z","started_at":"2020-05-10T19:26:33.127Z","finished_at":"2020-05-10T19:28:41.371Z","duration":128.244812,"queued_duration":1.36548,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899547","artifacts":[{"file_type":"trace","size":785,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899546,"status":"canceled","stage":"stage-1","name":"lint","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.515Z","started_at":"2020-05-10T19:26:32.888Z","finished_at":"2020-05-10T19:28:41.361Z","duration":128.472564,"queued_duration":1.14638,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899546","artifacts":[{"file_type":"trace","size":485,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899543,"status":"canceled","stage":"stage-1","name":"windows32","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.486Z","started_at":"2020-05-10T19:26:32.216Z","finished_at":"2020-05-10T19:28:41.347Z","duration":129.131756,"queued_duration":0.501053,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899543","artifacts":[{"file_type":"trace","size":65199,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":["windows-inria"]}
{"id":545899542,"status":"canceled","stage":"stage-1","name":"windows64","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.448Z","started_at":"2020-05-10T19:26:32.099Z","finished_at":"2020-05-10T19:28:41.334Z","duration":129.234609,"queued_duration":0.404345,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899542","artifacts":[{"file_type":"trace","size":66875,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":["windows-inria"]}
{"id":545899541,"status":"canceled","stage":"stage-1","name":"build:quick","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T19:26:30.417Z","started_at":"2020-05-10T19:26:32.825Z","finished_at":"2020-05-10T19:28:41.320Z","duration":128.494639,"queued_duration":1.148028,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899541","artifacts":[{"file_type":"trace","size":593024,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899540,"status":"canceled","stage":"stage-1","name":"build:base+async","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T19:26:30.394Z","started_at":"2020-05-10T19:26:32.788Z","finished_at":"2020-05-10T19:28:41.308Z","duration":128.520175,"queued_duration":1.130114,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899540","artifacts":[{"file_type":"trace","size":1222,"filename":"job.log","file_format":null}],"runner":{"id":44028,"description":"shared-runners-manager-3.gitlab.com","ip_address":"35.196.21.178","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899539,"status":"canceled","stage":"stage-1","name":"build:edge+flambda:dune:dev","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.375Z","started_at":"2020-05-10T19:26:32.747Z","finished_at":"2020-05-10T19:28:41.295Z","duration":128.547799,"queued_duration":1.106563,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899539","artifacts":[{"file_type":"trace","size":49318,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545899538,"status":"canceled","stage":"stage-1","name":"build:edge+flambda","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.355Z","started_at":"2020-05-10T19:26:32.201Z","finished_at":"2020-05-10T19:28:41.284Z","duration":129.083046,"queued_duration":0.579291,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899538","artifacts":[{"file_type":"trace","size":485,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899537,"status":"canceled","stage":"stage-1","name":"build:base+32bit","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.339Z","started_at":"2020-05-10T19:26:32.165Z","finished_at":"2020-05-10T19:28:41.272Z","duration":129.106782,"queued_duration":0.561936,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899537","artifacts":[{"file_type":"trace","size":485,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545899536,"status":"canceled","stage":"stage-1","name":"build:base","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T19:26:30.320Z","started_at":"2020-05-10T19:26:32.127Z","finished_at":"2020-05-10T19:28:41.258Z","duration":129.131421,"queued_duration":0.540944,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","short_id":"ba837b0e","created_at":"2020-05-10T21:26:11.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11490 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T21:26:11.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/ba837b0e3c335749e6a33c16f3bed837c9c12aa6"},"pipeline":{"id":144557572,"iid":15989,"project_id":6138686,"sha":"ba837b0e3c335749e6a33c16f3bed837c9c12aa6","ref":"pr-12294","status":"canceled","source":"push","created_at":"2020-05-10T19:26:30.301Z","updated_at":"2020-05-10T19:28:42.050Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144557572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545899536","artifacts":[{"file_type":"trace","size":1542,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
