[{"url":"https://api.github.com/repos/coq/coq/issues/comments/753651123","html_url":"https://github.com/coq/coq/issues/13711#issuecomment-753651123","issue_url":"https://api.github.com/repos/coq/coq/issues/13711","id":753651123,"node_id":"MDEyOklzc3VlQ29tbWVudDc1MzY1MTEyMw==","user":{"login":"JasonGross","id":396076,"node_id":"MDQ6VXNlcjM5NjA3Ng==","avatar_url":"https://avatars.githubusercontent.com/u/396076?v=4","gravatar_id":"","url":"https://api.github.com/users/JasonGross","html_url":"https://github.com/JasonGross","followers_url":"https://api.github.com/users/JasonGross/followers","following_url":"https://api.github.com/users/JasonGross/following{/other_user}","gists_url":"https://api.github.com/users/JasonGross/gists{/gist_id}","starred_url":"https://api.github.com/users/JasonGross/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/JasonGross/subscriptions","organizations_url":"https://api.github.com/users/JasonGross/orgs","repos_url":"https://api.github.com/users/JasonGross/repos","events_url":"https://api.github.com/users/JasonGross/events{/privacy}","received_events_url":"https://api.github.com/users/JasonGross/received_events","type":"User","site_admin":false},"created_at":"2021-01-03T17:39:07Z","updated_at":"2021-01-03T17:39:07Z","author_association":"MEMBER","body":"Note that wrapping the `repeat` in `try` does not eliminate the error, and this seems bogus.  Also the error message is under-informative; where does this constraint come from?","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/753651123/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}]