This is a fun one, if you wrap the Qed in Fail it says the command doesn't fail x_x
So it runs
- let v := ..., producing `v := @id Type@{1} ?bla`
- Axiom admit', producing `admit' : forall T : Type@{3}, T`
- exact admit', inferring universe constraint `1 < 3`
- reset environment to before the proof
- Axiom admit', producing `admit' : forall T : Type@{5}, T`
- save the above proof with `1 < 3`, but 3 doesn't exist

With `Fail` it doesn't reset the envionment + rerun Axiom, so universe 3 is still there and saving succeeds.
Possible solutions:
- make Fail run after resetting the environment + rerunning commands? There may be related bugs without using the universe counter because of this difference between Fail and non-Fail
- somehow remove the global, non-resettable universe counter
- some system which doesn't fully rerun commands inside proofs?
In coq-lsp [which just runs vernacinterp linearly] I get an anomaly on the first exact, already. interesting,

```
Conversion test raised an anomaly: Anomaly "Universe foo.3 undefined."
```
Probably missing some `update_global_env` call
I thought we had a very similar bug at some point, that was fixed IIRC. What you observe with `Fail` may be due to a different classification.
> Probably missing some `update_global_env` call

Uh, why is that needed? Does it mean that `Vernacentries.interp` is unsound as it stands?
The evar map has a copy of the universe graph, + the proof's local universes.
When you do something that declares global universes, such as Axiom, you need to update the evar map with the new universes.

This is related to https://github.com/coq/coq/issues/9455
Yeah so why is not the axiom code updating the corresponding evar maps? After all it has controlled access to the proof stack now.
We don't want random commands to mess with random proofs do we?
> We don't want random commands to mess with random proofs do we?

I am not sure what do you mean. Is there any other way?
update_sigma_env before accessing the proof, instead of after modifying the global env
Who should call `update_sigma_env`?
Current system works afaict
If you don't need to worry about the stm (like that ?proof thing) then interp_functional_vernac could do it
Umm, current system does not work; my LSP server hooks directly on `Vernacentries.interp` and I still get problems. So this is not a STM-specific problem.

We have many instances where the lower layers are buggy, then the upper layers [the STM] try to patch up, see for example the discard_proof stuff in the STM. I think I don't need to explain why this is not the best approach.
> If you don't need to worry about the stm (like that ?proof thing) then interp_functional_vernac could do it

Maybe I misunderstood the part of "current system works" vs "interp could do it".

What I was proposing if for interp to do it; but you answered "We don't want random commands to mess with random proofs"

So I am a bit lost.

For now I would be happy if `interp` was sound [forgetting about the `?proof` inject hack] , once we have a sound system we could think about optimizations, but not before.

This bug isn't about update_sigma_env so let's stop talking about it here.
Adding axioms in the middle of a proof is not supported. Can't we all agree on a simple thing like that? It broke badly in 8.5 due to universe polymorphism + STM.

My point is: the Coq parser let's you write almost everything. Why should this loose behavior define what is licit? Single instances of this phenomenon may look reasonable, but if you think about it, it lets you require ml code in the middle of a functor signature... The fact that it parses, and hence reaches the interpreter, be it linear or parallel, changes little to me. You can't possibly give a reasonable meaning to any sequence of parsed sentences. The fact that the STM tries to support some of these scenarios is, FTR, not my original intention/design. Was it in any pre 8.5 design? I bet no. 

Going back to the actual problem... sorry for the digression : Jason, we are all happy to receive minimized bug, but it also helps to understand what you were trying to achieve in your original use case. Why do you need to declare axioms in the middle of something in the first place? There may be, or we could provide, better working ways of achieving your goal.
> This bug isn't about update_sigma_env so let's stop talking about it here.

Is it not? You suggested it was due to it, or do you want me to open a different bug for the unsoundness on `interp` ?
> Adding axioms in the middle of a proof is not supported.

A problem here is that we don't have a proper list of "known issues" / "not supported stuff"

I tried to add one in #947 but didn't go so far.

I do agree that if something is not support then it should fail with an error message instead of producing an anomaly.
> A problem here is that we don't have a proper list of "known issues" / "not supported stuff"

Maybe it would be easier to define what is supported, i.e. a document grammar?
> I do agree that if something is not support then it should fail with an error message instead of producing an anomaly.

I fully agree. And I think the most civilized way is a parse error.
> Adding axioms in the middle of a proof is not supported. Can't we all agree on a simple thing like that?

Well indeed that may be tricky for example for the same reason users complained about the "deprecation" of nested proofs.

I am unfamiliar with the technical difficulties of supporting axioms inside a proof; why is it hard? 
> Jason, we are all happy to receive minimized bug, but it also helps to understand what you were trying to achieve in your original use case. Why do you need to declare axioms in the middle of something in the first place? 

When I have slow proof scripts, I sometimes want to prototype things by adding axioms without having to re-run the entire script.  I reported this because it's an anomaly; if you make it an error to close a proof with an axiom in the middle of it (as long as the error shows up at Qed-time and there is a warning and not an error at Axiom declaration time), I will not complain.
> if you make it an error to close a proof with an axiom in the middle of it (as long as the error shows up at Qed-time and there is a warning and not an error at Axiom declaration time), I will not complain.

Unfortunately @JasonGross this bug happens before Qed time too.
> I am unfamiliar with the technical difficulties of supporting axioms inside a proof; why is it hard?

The bug we see here is that the universes occurring in the type of the axiom have not only to be added to the global environment, but also the ongoing proof... and given that there is an anomaly, to some other piece of state...

The difficulty is that he only semantics we could give to that nested Axiom (or nested proof) is as if the Axiom was declared before the proof was started, but time traveling is still hard in 2019 ;-) It is a scope extrusion, that does work bad in imperative programming and does not work at all in functional programming. At least, this is my understanding of this class of bugs.
>The bug we see here is that the universes occurring in the type of the axiom have not only to be added to the global environment, but also the ongoing proof... and given that there is an anomaly, to some other piece of state...

That's the lsp bug, not the original bug.
> The difficulty is that he only semantics we could give to that nested Axiom (or nested proof) is as if the Axiom was declared before the proof was started, but time traveling is still hard in 2019 ;-) It is a scope extrusion, that does work bad in imperative programming and does not work at all in functional programming. At least, this is my understanding of this class of bugs.

Thanks for the explanation @gares , but I am not sure how this cannot work on a functional style. Why is not updating the proof stack after adding the axiom enough?

You may need some scoping on universes for this to work well tho.
> updating the proof stack after adding the axiom enough?

If your entire state is reified, then you can surely traverse it and patch it. Any piece of data that was synthesized looking at the data that changed has to be recomputed. One is the set of existing universes inside the evar_map: you have to patch all its copies referenced by your state, and all the data derived from it. Some other piece of state may not be reified, eg a hook to be called at proof closing (the outdated data may be in the closure).

Of course one can roll back, a re-execute things in the right order. This is sound, but from the user perspective it is as efficient as backtracking the script and placing the axiom were it belongs, that is before the proof starts. So this solution is not good either, or better it is as good as not supporting nested axioms at all, that is my preferred option.
> hook to be called at proof closing (the outdated data may be in the closure).

Interesting thanks, proof closing hooks and data in closures are gone in the PRs reflected in #10041 . Still there is quite a bit work but a lot more control over proof closing is possible after them.


This is basically the second part of #4603 (it's really 2 bugs in one) which was "fixed" in 927e88de465e94bf18b970b45faaf97b4c2dff82 by adding a special case for `Definition := ...`. Since here was with an axiom instead of a definition we see the limitations of this approach...
Good catch @SkySkimmer 
Note that any command with a side effect in the middle of a proof may need special treatment... So I'd say I can't possibly work to allow anything everywhere.
The problem still occurs with versions 8.13.2 and the current master branch, i.e. commit a1fac38181. Interestingly, if universe polymorphism is enabled, the anomaly doesnâ€™t arise. The problem might be easier to solve, if https://github.com/coq/ceps/pull/42 is implemented.

Regarding
> When I have slow proof scripts, I sometimes want to prototype things by adding axioms without having to re-run the entire script. I reported this because it's an anomaly; if you make it an error to close a proof with an axiom in the middle of it (as long as the error shows up at Qed-time and there is a warning and not an error at Axiom declaration time), I will not complain.

If declaring axioms in the middle of a proof were forbidden, you could work around this restriction using `assert` and `admit`.
Replacing `Axiom Foo : Bar.` with `assert Bar as Foo. { admit. }`.
